### ISSUE TITLE
Uncaught ReferenceError: ReactDOM is not defined

### ISSUE THREAD

**Issue by chandrahmani** [chandrahmani/hello-travel#7]
Uncaught ReferenceError: ReactDOM is not defined
    at main.jsx:6:1 

![image](https://user-images.githubusercontent.com/82306431/222882591-e744bb92-7bf6-424a-be0a-02cc43defa19.png)

**Comment by chandrahmani** [comment]
I was trying to implement `DOM` in the `React` package

**Comment by chandrahmani** [comment]
branch `feature-f1`

**Comment by JohnX4321** [comment]
There maybe an import error. I couldn't find this branch online. I can take a look if the code snippet for main.jsx is there

**Comment by hidaytrahman** [comment]
Hey, it was for demonstration, thank you for your quick response
